version: '3.1'
services:
  db:
    image: mysql
    container_name: email_api_mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - './email_data:/var/lib/mysql'
volumes:
  email: